FORMAT: 1A
HOST: https://wio.seeed.io

# wio API reference
Wio IOT 平台是一款物联网应用平台，真正的WOT产品。Restful API帮助用户完成产品定义和部署。

## 端点
API请求的端点为

    https://wio.seeed.io/v2
    
所有的返回都为json格式。
## Token
每个请求都需要带上认证信息，有两种方式携带认证信息。
- 在`Header`添加`Authorization`，例如：

        Authorization: token 313be000160b425baf933d47e12b1e9e
        
- 在请求参数中添加`access_token`，例如：
        
        https://wio.seeed.io/v2/user?access_token=313be000160b425baf933d47e12b1e9e
        
## 响应码
API完全遵循HTTP 状态码协议规定，不同响应码：

状态码 | 描述
---|---
200 | OK，正常响应
201 | Created，资源创建成功
202 | Accepted，请求已接受，后台服务正在处理
302 | Retry，重定向
400 | Error，出现错误，会带上错误消息
403 | Forbidden，没有访问资源的权限
404 | Not Found，没有发现资源
500 | Internal Server Error，系统错误，服务器停止

## 时间格式
时间采用`ISO8601`格式。如`YYYY-MM-DDTHH:MM:SSZ`

# /v2/users{?page,per_page}

+ Parameters
    + page (optional) - A query variable
    + per_page (optional) - Another query variable

## 获取所有用户信息 [GET]
以创建用户顺序列出所有用户信息。
注意只有认证用户为系统管理员时，才会返回所有用户信息。

+ Response 200 (application/json)

    + Headers
        
            Link: <http://wio.seeed.io/v2/resource?page=2>; rel="next",<http://wio.seeed.io/v2/resource?page=5>; rel="last"
            
    + Body
    
            {
              "users": [
                {
                  "user_id": "057ee4457d754b049c1bbfb4ddd5412a",
                  "created_at": "2016-10-26T02:27:33Z"
                }
              ]
            }

# /v2/user

## 获取认证用户信息 [GET]
列出当前认证用户的信息

+ Response 200 (application/json)

        {
          "user_id": "057ee4457d754b049c1bbfb4ddd5412a",
          "created_at": "2016-10-26T02:27:33Z"
        }

# /v2/user/token
## 获取认证用户的所有令牌信息 [GET]

# /v2/things
## 获取用户的所有节点设备 [GET]

+ Parameters
    + page (optional) - A query variable
    + per_page (optional) - Another query variable
    
## 创建新设备 [POST]
### 输入
| 名字 | 类型 | 描述 |
| ------| ------ | ------ |
| board | string | **Required**. 节点设备型号名字 |
| name | string | 节点设备名字 |

+ Request (application/json)

        {
          "board": "WioLink v1.0"
        }
        
+ Response 201 (application/json)

    + Headers
    
            Location: https://wio.seeed.io/v2/things/473a3a7ec7a54a33b60e4a57be5d0a27
            
    + Body
    
            {
              "thing_id": "473a3a7ec7a54a33b60e4a57be5d0a27",
              "user_id": "057ee4457d754b049c1bbfb4ddd5412a",
              "firmware_id": null,
              "key": "6cf42c96de4c4250864ec4eabf7fca26",
              "name": "",
              "board": "WioLink v1.0",
              "online": false,
              "pp_id": null,
              "well_known": "",
              "shared": false,
              "created_at": "2016-10-27T08:24:36Z",
              "updated_at": "2016-10-27T08:24:36Z"
            }
            
            
# /v2/things/{thing_id}

+ Parameters
    + thing_id (string) - 设备ID
    
## 获取设备信息 [GET]
## 更新设备信息 [PATCH]
## 删除节点设备 [DELETE]

# /v2/firmwares
## POST [POST]
# /v2/firmwares/{firmware_id}
## GET [GET]
# /v2/firmwares/{firmware_id}/ulbs
## GET [GET]
# /v2/firmwares/{firmware_id}/ulbs/{path}
## GET [GET]
# /v2/firmwares/{firmware_id}/bin
## GET [GET]
# /v2/bins/{sha}
## GET [GET]
